### PR TITLE
Fix emscripten permission issue

### PR DESCRIPTION
**Pull request by malbarbo**
Fixes https://github.com/japaric/cross/issues/110

### CODE REVIEW

**Comment by japaric** [comment]
Thanks for the PR, @malbarbo. LGTM.

I allowed failures in the wasm and asmjs builds in #105 which is about to land. Please undo that part in this PR then you can r+ this yourself.

@homunkulus delegate+

**Comment by homunkulus** [comment]
:v: @malbarbo can now approve this pull request

**Comment by malbarbo** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit f0ed74c has been approved by `malbarbo`

**Comment by homunkulus** [comment]
:hourglass: Testing commit f0ed74c with merge f0ed74c...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/cross/builds/278326440?utm_source=github_status&utm_medium=notification)

**Comment by japaric** [comment]
Yes, I think so. I have restarted that build job.

**Comment by japaric** [comment]
:-( too late. The other PR is being tested so the build can't be resumed (the auto branch tip changed).

@homunkulus retry

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 7daa8f0 has been approved by `japaric`

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit fba15a8 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit fba15a8 with merge 3fdf267...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/cross/builds/278562348?utm_source=github_status&utm_medium=notification)
Approved by: japaric
Pushing 3fdf267ccb97dc7dabadc8613d20ed9f68eb2b14 to master...

**Comment by jan-hudec** [comment]
@japaric, did the build push out the Docker image? I've tried again, but I am *still getting the same error*: https://travis-ci.org/rust-locale/locale_config/jobs/278730580

**Comment by japaric** [comment]
@jan-hudec you won't get these changes until I release a new Cross version. I'll do so later today.

**Comment by jan-hudec** [comment]
@japaric, thanks, I'll try later then.

**Comment by japaric** [comment]
@jan-hudec it should work now

**Comment by jan-hudec** [comment]
@japaric, yes, looks good now. Thanks.

**Pull request merged**
