### PR TITLE
arm-musl support

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit ad1d53f has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit ad1d53f with merge ad1d53f...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/cross/builds/194897407)

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 447eec3 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 447eec3 with merge 447eec3...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/cross/builds/197692270)

**Comment by homunkulus** [comment]
:umbrella: The latest upstream changes (presumably #64) made this pull request unmergeable. Please resolve the merge conflicts.

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit db5f236 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit db5f236 with merge db5f236...

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 7a9c96f has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 7a9c96f with merge 7a9c96f...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/cross/builds/199095587)

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit ac6a1a3 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit ac6a1a3 with merge ac6a1a3...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/cross/builds/199234795)
Approved by: japaric
Pushing ac6a1a3b445c5ec925b6a3829eeea5b28067cf6f to master...

**Pull request merged**
