### PR TITLE
don't depend on binfmt_misc when using a recent toolchain

### LINKED ISSUE #118: Avoiding the binfmt_misc dependency
It turns out that you can avoid needing binfmt_misc support for cross-testing by setting the target's runner in Cargo to `qemu-<FOO>-static`. Example for ARM: https://github.com/sfackler/rust-openssl/commit/8450cfbb528dabdbf9bda21f7add718c13faac8a

### PR DESCRIPTION
**Pull request by japaric**
closes #118

cc @sfackler

One thing that's missing in this PR is some version check to fall back to the
old binfmt_misc logic when cross is used with a Rust toolchain that doesn't
support the Cargo runner feature.

Alternatively, we could release this as v0.2.0 and require a Rust toolchain
version equal or greater than 1.19.

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit acc37aa has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit acc37aa with merge 3ecee92...

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 8a2bcaa has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 8a2bcaa with merge 0f197f7...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/cross/builds/278271540?utm_source=github_status&utm_medium=notification)

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 0ee902f has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 0ee902f with merge 7daa8f0...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/cross/builds/278356621?utm_source=github_status&utm_medium=notification)

**Comment by japaric** [comment]
Spurious MIPS failure but the runner seems to be working. The rest of tests passed so I'm going to merge manually.

**Pull request merged**
