### PR TITLE
Fix binfmt_misc link

### LINKED ISSUE #87: binfmt doc link broken
When I try to visit https://www.kernel.org/doc/Documentation/binfmt_misc.txt , I get 404 http status.

### PR DESCRIPTION
**Pull request by malbarbo**
Fixes #87.

### CODE REVIEW

**Comment by japaric** [comment]
Thanks, @malbarbo!

@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit b5376fe has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit b5376fe with merge b5376fe...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/cross/builds/222232750)

**Comment by japaric** [comment]
Tests were broken due to changes in the compiler-builtins crate but I've fixed them in #89.

@homunkulus retry

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:bangbang: Invalid head SHA found, retrying: `0000000000000000000000000000000000000000`

**Comment by homunkulus** [comment]
:pushpin: Commit b5376fe has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit b5376fe with merge 9426dc0...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/cross/builds/222282148)
Approved by: japaric
Pushing 9426dc0b3223ddcef810ddb36bb5e824871b0423 to master...

**Pull request merged**
