### PR TITLE
add support for `cross build`ing `thumbv*-none-eabi*` targets

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 2843588 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 2843588 with merge 2843588...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/cross/builds/187835380)
Approved by: japaric
Pushing 28435882ddb50c329024c2ed2d18a82756528993 to master...

**Pull request merged**
