### PR TITLE
bump openssl to 1.0.2k

### LINKED ISSUE #79: Update openssl to 1.0.2k

### PR DESCRIPTION
**Pull request by japaric**
closes #79

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 335ea15 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 335ea15 with merge 335ea15...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/cross/builds/217803090)

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 45e1c92 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 45e1c92 with merge 45e1c92...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/cross/builds/217918637)
Approved by: japaric
Pushing 45e1c92216943b3774cc178edbd0468e0b084c53 to master...

**Pull request merged**
