### PR TITLE
unconditionally generate a lockfile

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 2927a37 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 2927a37 with merge 2927a37...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/cross/builds/191851078)
Approved by: japaric
Pushing 2927a372b79da51482e3e58cc1f41a0027c991e1 to master...

**Pull request merged**
