### PR TITLE
add option to Cross.toml to use Xargo instead of Cargo

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit f68d421 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit f68d421 with merge f68d421...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/cross/builds/190613468)

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 10c7dcc has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 10c7dcc with merge 10c7dcc...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/cross/builds/190644414)
Approved by: japaric
Pushing 10c7dcc3cba4d8d2dd048b5c9708b3e1a116c702 to master...

**Pull request merged**
