### PR TITLE
install more packages on the thumb*-none-eabi* images

### PR DESCRIPTION
**Pull request by japaric**
- gcc + libc6-dev to be able to build build scripts

- libnewlib-dev to be able to cross compile C code for these targets

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 2033c73 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 2033c73 with merge 2033c73...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/cross/builds/187905417)
Approved by: japaric
Pushing 2033c73d2488a9d04d072b87bfbe7ab2c3a8b357 to master...

**Pull request merged**
