### PR TITLE
simplify logic using enums

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit acd6e87 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit acd6e87 with merge acd6e87...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/cross/builds/186831723)
Approved by: japaric
Pushing acd6e87296751ae2d032fe727943246dfa6b11af to master...

**Pull request merged**
