### PR TITLE
add `cross build` support for some *BSD targets

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 6538af7 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 6538af7 with merge 6538af7...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/cross/builds/189907124)

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 795a1eb has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 795a1eb with merge 795a1eb...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/cross/builds/189915479)
Approved by: japaric
Pushing 795a1eb59f53db5d57be824a92a32b9c97b2142b to master...

**Pull request merged**
