### PR TITLE
compiler-builtins test requires the gen-tests Cargo feature

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 813aeb8 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 813aeb8 with merge 813aeb8...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/cross/builds/222267731)
Approved by: japaric
Pushing 813aeb808aa1b9ba94365a82ffc8321b8aa768b6 to master...

**Pull request merged**
