### PR TITLE
add support for the `arm-unknown-linux-gnueabi` target

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 421dc4c has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 421dc4c with merge 421dc4c...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/cross/builds/188136537)
Approved by: japaric
Pushing 421dc4c80f56d7775a7f277531b12f5d87515409 to master...

**Pull request merged**
