### PR TITLE
mips/ppc64: override the latest curl-sys version

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit e3fa762 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit e3fa762 with merge e3fa762...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/cross/builds/198248305)
Approved by: japaric
Pushing e3fa7627fb1024c76f8350ca99b7228f97d4a945 to master...

**Pull request merged**
