### PR TITLE
add the x86_64-linux target to CI for real

### PR DESCRIPTION
**Pull request by japaric**
cc #126

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 43e84ae has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 43e84ae with merge 43e84ae...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/cross/builds/278950049?utm_source=github_status&utm_medium=notification)
Approved by: japaric
Pushing 43e84aeea4427572d3ae851085415c2a28d94b46 to master...

**Pull request merged**
