### PR TITLE
upgrade OpenSSL to 1.0.2m

### PR DESCRIPTION
**Pull request by japaric**
closes #142

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 8088695 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 80886958fb703f8e98ba70832bb0614334b016ba with merge 2a8ea48d62f2817555f4004bb536bf54977a798c...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/cross/builds/297303963?utm_source=github_status&utm_medium=notification)
Approved by: japaric
Pushing 2a8ea48d62f2817555f4004bb536bf54977a798c to master...

**Pull request merged**
