### PR TITLE
remove curl-sys overrides

### PR DESCRIPTION
**Pull request by japaric**
on mips and ppc64 as alexcrichton/curl-rust#137 has landed

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 8d60198 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 8d60198 with merge b6d6166...

**Comment by homunkulus** [comment]
:boom: Test timed out

**Comment by japaric** [comment]
Travis test passed.

**Pull request merged**
