### PR TITLE
move to Xargo v0.3.5

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 60f7854 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 60f7854 with merge 60f7854...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/cross/builds/193931823)

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 98dc884 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 98dc884 with merge ebee639...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/cross/builds/194015043)
Approved by: japaric
Pushing ebee63952e7b9a56fff2fed021083dc05a0bb913 to master...

**Pull request merged**
