### PR TITLE
add `libnewlib-arm-none-eabi` dep to thumb* targets.

### PR DESCRIPTION
**Pull request by Emilgardis**
Adds `libc.a`, `libm.a`, `crt0.o` and more.

This adds 73.17 MB to the image however.

### CODE REVIEW

**Comment by japaric** [comment]
Thanks, @Emilgardis!

@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 5853c6b has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 5853c6b with merge 5853c6b...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/cross/builds/189553104)
Approved by: japaric
Pushing 5853c6bac66ea9889ecc62e4eeaf82605932a1c9 to master...

**Pull request merged**
