### PR TITLE
fix: logic that decides when to register QEMU interpreters

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 89181f6 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 89181f6 with merge 89181f6...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/cross/builds/192002498)
Approved by: japaric
Pushing 89181f63b914f37638452ca8d7ae5ed04de0f490 to master...

**Pull request merged**
