### PR TITLE
fix the sparc64 linker

### PR DESCRIPTION
**Pull request by japaric**
cc #127

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 609e157 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 609e157 with merge 2310460...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/cross/builds/278964368?utm_source=github_status&utm_medium=notification)
Approved by: japaric
Pushing 2310460e5dc6fcc0e7ca12f17b0537cb557bf1ac to master...

**Pull request merged**
