### PR TITLE
support crossing from x86_64 osx to i686 osx

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 4322799 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 4322799 with merge 4322799...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/cross/builds/186890288)

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 69fc4fe has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 69fc4fe with merge 69fc4fe...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/cross/builds/186980947)
Approved by: japaric
Pushing 69fc4feefcd8c6169b29efd13f1d417550a91e27 to master...

**Pull request merged**
