### PR TITLE
Improve pc-windows-gnu support

### PR DESCRIPTION
**Pull request by malbarbo**
Fixes https://github.com/japaric/cross/issues/65

### CODE REVIEW

**Comment by malbarbo** [comment]
Hey @japaric, I gave a try in improving pc-windows-gnu support.

There two question to be solved. First, the produced binaries are not static linked, they depend on some dlls. I think it's possible to produce static linked binaries passing `-static -static-libgcc -static-libstdc++` to the linker. Second, the openssl tests passes (in my machine) but there is no build (or source) for openssl... What is going on in this case?

**Comment by japaric** [comment]
Thanks for the PR @malbarbo! This looks good to me.

> First, the produced binaries are not static linked, they depend on some dlls.

We should stick to the default. Not sure if the binaries compiled for mingw on a Windows host produce statically linked binaries but we should do the same.

> What is going on in this case?

I have no idea. Perhaps the openssl crate now builds libopenssl on the fly for windows targets? Do you know if `cross build`ing Cargo works? i.e. does it link properly and the produced binary actually works on a windows machine? If it does then we can keep things as they are and mark openssl as supported for this target on the README. Otherwise, we simply don't claim openssl support for these targets.

Oh, and could you add the i686-mingw target to the list of supported targets in the README?

**Comment by malbarbo** [comment]
README updated. I do not have access to a windows machine to test if cargo works... I built and run cargo with wine in my machine and it worked fine. I left out openssl support in README. If someone can confirm that it works, then we update it later.

**Comment by japaric** [comment]
> I built and run cargo with wine in my machine and it worked fine.

Thanks for checking.

> I left out openssl support in README. If someone can confirm that it works, then we update it later.

Sounds good to me.

@homunkulus r+
cc @nagisa ^ support for the missing i686-mingw

**Comment by homunkulus** [comment]
:pushpin: Commit 3d3ec4d has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 3d3ec4d with merge 3d3ec4d...

**Comment by malbarbo** [comment]
@japaric Another try. Mount binfmt_misc before before register wine interpreter.

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 049447c has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 049447c with merge 049447c...

**Comment by malbarbo** [comment]
@japaric Sorry for being lazy... Now I have tested docker wine registration process in my machine.

**Comment by malbarbo** [comment]
I will try to reduce the build time.

**Comment by japaric** [comment]
> Sorry for being lazy

Don't be. I know the registration stuff is tricky since it latches so sometimes it seems to be working without having configured anything but actually it may have been configured before by some other program, etc.

> I will try to reduce the build time.

Yeah, we need to reduce build time to fit the 50 mins time limit or this can't land.

**Comment by malbarbo** [comment]
@japaric Ready for another try.

**Comment by japaric** [comment]
@malbarbo Sorry for the delay! Let's try again.

@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 09cb7be has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 09cb7be with merge 09cb7be...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/cross/builds/227049567?utm_source=github_status&utm_medium=notification)

**Comment by malbarbo** [comment]
x86_64 seems to be llvm 4 related, see https://github.com/rust-lang/rust/issues/41630. Unset DYLIB, compiler-builtins does pass anyway. Try to improve i686 built time. Maybe we can build another crate, cargo takes too long.

**Comment by malbarbo** [comment]
Let's give it another try?

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 7ddfddd has been approved by `japaric`

**Comment by homunkulus** [comment]
:lock: Merge conflict

**Comment by homunkulus** [comment]
:umbrella: The latest upstream changes (presumably #96) made this pull request unmergeable. Please resolve the merge conflicts.

**Comment by malbarbo** [comment]
Rebase.

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 1c94fc7 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 1c94fc7 with merge 1c94fc7...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/cross/builds/234379761?utm_source=github_status&utm_medium=notification)

**Comment by homunkulus** [comment]
:umbrella: The latest upstream changes (presumably #98) made this pull request unmergeable. Please resolve the merge conflicts.

**Comment by malbarbo** [comment]
Can we try again?

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 3c68814 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 3c68814 with merge 3c68814...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/cross/builds/238797798?utm_source=github_status&utm_medium=notification)

**Comment by malbarbo** [comment]
I do not want to give up... Can we try again?

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 068a819 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 068a819 with merge 068a819...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/cross/builds/239090817?utm_source=github_status&utm_medium=notification)

**Comment by malbarbo** [comment]
We are not building openssl on *-pc_windows-gnu, so disable testing it. This should allows i686-pc-windows-gnu build on time.

https://github.com/rust-lang/cargo/pull/4126 has landed, so we are ready to try again...

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 68c0bc1 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 68c0bc1 with merge 68c0bc1...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/cross/builds/239707834?utm_source=github_status&utm_medium=notification)
Approved by: japaric
Pushing 68c0bc1dd6589d7f8c9016ede573747efc3e0d94 to master...

**Pull request merged**
