### PR TITLE
rename a CommandExt method, update README

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 5d3d61e has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 5d3d61e with merge ad3a2b1...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/cross/builds/187341851)

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 90066c6 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 90066c6 with merge 90066c6...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/cross/builds/187346006)
Approved by: japaric
Pushing 90066c6774ef747427e0c18c5676154fea65e588 to master...

**Pull request merged**
