### PR TITLE
support custom targets

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 1874b54 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 1874b54 with merge 1874b54...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/cross/builds/193627441)

**Comment by japaric** [comment]
@homunkulus retry

**Comment by homunkulus** [comment]
:hourglass: Testing commit 1874b54 with merge 1874b54...

**Comment by japaric** [comment]
@homunkulus retry

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 670030a has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 670030a with merge 670030a...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/cross/builds/193732361)
Approved by: japaric
Pushing 670030a5e45bede7cd4d7d40b5d8c8ec6876ecda to master...

**Pull request merged**
