### PR TITLE
fix deploys

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 3b801f3 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 3b801f3 with merge 3b801f3...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/cross/builds/186732462)
Approved by: japaric
Pushing 3b801f3f28245a0b6c1d2c70b4603542b952d8b1 to master...

**Pull request merged**
