### PR TITLE
tag docker images using the 'v{}' format

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit f75f1f0 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit f75f1f0 with merge f75f1f0...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/cross/builds/186806857)
Approved by: japaric
Pushing f75f1f0c7647815abdc2de88de7e79b341e3135b to master...

**Pull request merged**
