### PR TITLE
Add subcommand 'deb'

### PR DESCRIPTION
**Pull request by lexxvir**
This commit adds possibility to
use 'cargo deb' to build debian
packages in Docker image.

cargo-deb project:
https://github.com/mmstick/cargo-deb

### CODE REVIEW

**Comment by japaric** [comment]
Thanks, @lexxvir.

@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit b86207e has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit b86207e with merge b86207e...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/cross/builds/281872758?utm_source=github_status&utm_medium=notification)

**Comment by homunkulus** [comment]
:hourglass: Testing commit b86207ece24e5eb607b9283c8ae674cb0f7cc167 with merge 2489a59f2f13a138358668348392ed922d50cb29...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/cross/builds/284859110?utm_source=github_status&utm_medium=notification)

**Comment by japaric** [comment]
that error should be fixed in #135 so let's try again

@homunkulus retry

**Comment by homunkulus** [comment]
:hourglass: Testing commit b86207ece24e5eb607b9283c8ae674cb0f7cc167 with merge aaa6f0df94039e1deef55a53d529823fb94b6487...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/cross/builds/285203859?utm_source=github_status&utm_medium=notification)

**Comment by japaric** [comment]
@homunkulus retry

**Comment by homunkulus** [comment]
:hourglass: Testing commit b86207ece24e5eb607b9283c8ae674cb0f7cc167 with merge b3661b68fae3276043712905782f0e9d268faec3...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/cross/builds/285241403?utm_source=github_status&utm_medium=notification)
Approved by: japaric
Pushing b3661b68fae3276043712905782f0e9d268faec3 to master...

**Comment by vi** [comment]
Although `cross deb` shows the similar message as `cross deb1234`, it takes longer to run, so maybe it tries...

How do I actually use `cross deb`?

**Pull request merged**
