### PR TITLE
test i686-musl and 32-bit osx

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 8ab1955 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 8ab1955 with merge 8ab1955...

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit f317821 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit f317821 with merge f317821...

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 7610d03 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 7610d03 with merge 7610d03...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/cross/builds/187988795)
Approved by: japaric
Pushing 7610d0309210b4e13fb74b7415039d168ef64b06 to master...

**Pull request merged**
