### PR TITLE
support `asmjs-unknown-emscripten` and `wasm32-unknown-emscripten`

### PR DESCRIPTION
**Pull request by japaric**
cc @brson

`cross build --target asmjs-unknown-emscripten` and `node hello.js` works.

`cross test --target asmjs-unknown-emscripten` (and `cross run`) *would* Just Work *if* `rustc` generated executable `.js` files with a `#!/usr/bin/env node` shebang in it.

`cross build --target wasm-unknown-emscripten` succeeds but its output fails to run using `node`:

```
$ node target/wasm32-unknown-emscripten/release/hello.js
trying binaryen method: native-wasm
no native wasm support detected

/home/japaric/tmp/hello/target/wasm32-unknown-emscripten/release/hello.js:462
      throw ex;
      ^
no binaryen method succeeded. consider enabling more options, like interpreting, if you want that: https://github.com/kripken/emscripten/wiki/WebAssembly#binaryen-methods
```

Is this a regression? @brson reported that `node hello.wasm.js` worked way back in [this thread](https://users.rust-lang.org/t/compiling-to-the-web-with-rust-and-emscripten/7627).

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus try

**Comment by homunkulus** [comment]
:hourglass: Trying commit 4de2d6e with merge 4de2d6e...

**Comment by japaric** [comment]
> The job exceeded the maximum time limit for jobs, and has been terminated.

😢

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/cross/builds/188856888)

**Comment by homunkulus** [comment]
:umbrella: The latest upstream changes (presumably 5d70947) made this pull request unmergeable. Please resolve the merge conflicts.

**Comment by japaric** [comment]
> cross build --target wasm-unknown-emscripten succeeds but its output fails to run using node:

I figured out how to run this output using node. You need to build node from [this branch](https://github.com/v8/node/tree/vee-eight-lkgr) and pass the `--expose-wasm` flag to node (hat tip to @chicoxyzzy):

```
$ node --expose-wasm hello-fbbdd13f43d45d24.js
trying binaryen method: native-wasm
binaryen method succeeded.
Hello, world!
```

The weird part is that it expects the `.wasm` file that Cargo also outputs to be in *the same directory* as the `.js` file ... so this doesn't work:

```
$ ls target/wasm32-unknown-emscripten/release/
build  deps  examples  hello.js  native

$ node --expose-wasm target/wasm32-unknown-emscripten/release/hello.js
trying binaryen method: native-wasm
failed to compile wasm module: Error: ENOENT: no such file or directory, open 'hello-fbbdd13f43d45d24.wasm'

/mnt/hello/target/wasm32-unknown-emscripten/release/hello.js:462
      throw ex;
      ^
no binaryen method succeeded. consider enabling more options, like interpreting, if you want that: https://github.com/kripken/emscripten/wiki/WebAssembly#binaryen-methods
```

Nor this:

```
$ ls target/wasm32-unknown-emscripten/release/deps/
hello-fbbdd13f43d45d24.asm.js  hello-fbbdd13f43d45d24.wasm
hello-fbbdd13f43d45d24.js      hello-fbbdd13f43d45d24.wast

$ node --expose-wasm target/wasm32-unknown-emscripten/release/deps/hello-fbbdd1
3f43d45d24.js
trying binaryen method: native-wasm
failed to compile wasm module: Error: ENOENT: no such file or directory, open 'hello-fbbdd13f43d45d24.wasm'

/mnt/hello/target/wasm32-unknown-emscripten/release/deps/hello-fbbdd13f43d45d24.js:462
      throw ex;
      ^
no binaryen method succeeded. consider enabling more options, like interpreting, if you want that: https://github.com/kripken/emscripten/wiki/WebAssembly#binaryen-methods
```

It has to be executed like this:

```
$ cd target/wasm32-unknown-emscripten/release/deps

$ node --expose-wasm hello-fbbdd13f43d45d24.js
trying binaryen method: native-wasm
binaryen method succeeded.
Hello, world!
```

Which pretty much precludes `cargo run` and `cargo test` from working with this target.

**Comment by chicoxyzzy** [comment]
Hi Jorge!

I haven't tried using cross yet but I think I can provide some information that may (or may not) be useful for it as well. Looks like currently it's not possible to use `-o` option with file target using cargo (`cargo rustc --target=wasm32-unknown-emscripten -- -o hello.html` for example). Without `-o` option it's impossible to compile to HTML.
```bash
$ cargo rustc --target=wasm32-unknown-emscripten -- -o wasm.html
   Compiling wasm-test3 v0.1.0 (file:///Users/Chico/Projects/wasm-test3)
warning: ignoring specified output filename because multiple outputs were requested

warning: ignoring --out-dir flag due to -o flag.
```

**Comment by japaric** [comment]
@chicoxyzzy Hmm, if `emcc` provides another way to make it output html, you could use `cargo rustc --target wasm32-unknown-emscripten -- -C link-arg=$flag-for-emscripten`.

**Comment by japaric** [comment]
rebased. This will likely not land because of timeouts but let's try anyway.

@homunkulus r+

**Comment by homunkulus** [comment]
:hourglass: Testing commit 9491053 with merge 9491053...

**Comment by homunkulus** [comment]
:pushpin: Commit a866006 has been approved by `japaric`

**Comment by homunkulus** [comment]
:boom: Test timed out

**Comment by homunkulus** [comment]
:umbrella: The latest upstream changes (presumably #81) made this pull request unmergeable. Please resolve the merge conflicts.

**Comment by jan-hudec** [comment]
Since https://github.com/rust-lang/cargo/pull/3954 got merged, setting

```toml
[target.asmjs-unknown-emscripten]
linker = "emcc"
runner = "node"
```

makes `cargo test --target asmjs-unknown-emscripten` work.

Per comments above, with the right version of `node`, the following should make `cargo test --target wasm32-unknown-emscripten` work too:

```toml
[target.wasm32-unknown-emscripten]
linker = "emcc"
runner = "node --expose-wasm"
```

**Comment by japaric** [comment]
Closing is favor of #106

**Pull request closed without merging**
