### PR TITLE
add support for i686-musl

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 17abfe3 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 17abfe3 with merge 17abfe3...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/cross/builds/187937053)

**Comment by japaric** [comment]
@homunkulus retry

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 550ba06 has been approved by `japaric`

**Comment by homunkulus** [comment]
:pushpin: Commit 17abfe3 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 17abfe3 with merge 17abfe3...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/cross/builds/187947770)
Approved by: japaric
Pushing 17abfe3c6dd4b085e13cd8b7be60d4168d772302 to master...

**Pull request merged**
