### PR TITLE
s390x-linux supports openssl v0.7

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 9c16d63 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 9c16d63 with merge 9c16d63...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/cross/builds/199833648)
Approved by: japaric
Pushing 9c16d63607cd5b15671d54d4c2c14b85a0b8f1bc to master...

**Pull request merged**
