### PR TITLE
tweak deploys

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit ad1ef51 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit ad1ef51 with merge ad1ef51...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/cross/builds/186726655)
Approved by: japaric
Pushing ad1ef5123c9cd94bfe3e2db0d8ae22a3aa71f9ac to master...

**Pull request merged**
