### PR TITLE
homu support

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 5ef5fdd has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 5ef5fdd with merge 5ef5fdd...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/cross/builds/186716929)

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit acc695a has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit acc695a with merge acc695a...

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit bee19d6 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit bee19d6 with merge bee19d6...

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit e47e9f4 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit e47e9f4 with merge e47e9f4...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/cross/builds/186719330)
Approved by: japaric
Pushing e47e9f4298ff7312e2fffc67eba3a071140fb3e3 to master...

**Pull request merged**
