### PR TITLE
test the x86_64-musl target

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 7bb7973 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 7bb7973 with merge 19671cb...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/cross/builds/186894882)
Approved by: japaric
Pushing 19671cbf930c70ad8e170c5d0792f262cd6bc44a to master...

**Pull request merged**
