### PR TITLE
Fixes permission issues with userns on Docker host

### LINKED ISSUE #90: Issues with Docker Daemon when user namespace is enabled
When the Docker daemon has [user namespace](https://docs.docker.com/engine/reference/commandline/dockerd/#daemon-user-namespace-options) enabled, the following will fail

 - Reading/writing to bind mount volumes
 - `--privileged` flag

The fix is as simple as adding `--userns=host` to the `docker` command. BUT this will break on older Docker client versions that do not support this. I can probably fix this easily, but I am not sure how I should proceed.

EDIT: I suggest this: Use a `lazy_static` or something similar to do a docker engine version check. (`docker version --format '{{.Server.APIVersion}}'`) Then if the semver is newer than `1.24`, we automatically add the flag `--userns=host`.

### PR DESCRIPTION
**Pull request by lawliet89**
Fixes #90 

Please let me know if this approach is not satisfactory.
 - I added two new dependencies
 - I am not sure how we can test this

### CODE REVIEW

**Comment by japaric** [comment]
@lawliet89 Sorry for the delay!

This looks good to me.

@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 47c562e has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 47c562e with merge 47c562e...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/cross/builds/232271295?utm_source=github_status&utm_medium=notification)

**Comment by lawliet89** [comment]
Not sure what failed on powerpc. Seem to be the same issue for the other PRs too.

**Comment by japaric** [comment]
That should be fixed now.

@homunkulus r+

**Comment by homunkulus** [comment]
:bangbang: Invalid head SHA found, retrying: `0000000000000000000000000000000000000000`

**Comment by homunkulus** [comment]
:pushpin: Commit 47c562e has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 47c562e with merge 1ecf0e4...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/cross/builds/233264147?utm_source=github_status&utm_medium=notification)
Approved by: japaric
Pushing 1ecf0e4e7be8e2fbde13bd54f9c8ff8274ea14b8 to master...

**Pull request merged**
