### PR TITLE
add support for x86_64-pc-windows-gnu

### PR DESCRIPTION
**Pull request by japaric**
cc #65
cc @nagisa

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit c766b3f has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit c766b3f with merge c766b3f...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/cross/builds/199502134)

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:bulb: This pull request was already approved, no need to approve it again.

- This pull request previously failed. You should add more commits to fix the bug, or use `retry` to trigger a build again.

**Comment by homunkulus** [comment]
:pushpin: Commit c766b3f has been approved by `japaric`

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 836fad6 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 836fad6 with merge 836fad6...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/cross/builds/199679832)
Approved by: japaric
Pushing 836fad6ba074d81664aea2a296eb9a6def68259d to master...

**Pull request merged**
