### PR TITLE
generate lockfile when necessary

### LINKED ISSUE #37: Automatically generate a lock file
if there isn't one at the root of the Cargo project.

### PR DESCRIPTION
**Pull request by japaric**
closes #37

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 5d70947 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 5d70947 with merge 5d70947...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/cross/builds/188915585)
Approved by: japaric
Pushing 5d709476342afa353bfa7cd598443fa58086a966 to master...

**Pull request merged**
