### PR TITLE
Update OpenSSL to version 1.0.2l

### PR DESCRIPTION
**Pull request by bgermann**

### CODE REVIEW

**Comment by japaric** [comment]
Thanks, @bgermann.

@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 5471139 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 5471139a6baf9945dd61ccd4603e41408328df8a with merge 2c90ac64eff4b975fa12cd7cbefee0e0f0d4ba8f...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/cross/builds/292826709?utm_source=github_status&utm_medium=notification)

**Comment by malbarbo** [comment]
Maybe https://github.com/rust-lang/rust/issues/45500

**Comment by japaric** [comment]
I can repro the link error with 2017-10-23 but not with the today's nightly so let's try again.

@homunkulus retry

**Comment by homunkulus** [comment]
:hourglass: Testing commit 5471139a6baf9945dd61ccd4603e41408328df8a with merge 5aed9de773009b230d4582946a203ec23e16a99b...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/cross/builds/294568755?utm_source=github_status&utm_medium=notification)

**Comment by homunkulus** [comment]
:hourglass: Testing commit 5471139a6baf9945dd61ccd4603e41408328df8a with merge 95d20778dc12f834b44a20f5870a9a37fbb2b1d9...

**Comment by japaric** [comment]
The wasm target is broken due to rust-lang/cargo#4689. I think we can work around the issue by pinning to an older nightly.

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/cross/builds/295391790?utm_source=github_status&utm_medium=notification)

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 9c9bca6 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 9c9bca699882f940b80ac481ea0c8a45748b6731 with merge 61d79052252c00ef6f443da2d2582eaf9fb3bca6...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/cross/builds/295414240?utm_source=github_status&utm_medium=notification)

**Comment by japaric** [comment]
Running Hello, world! for `i686-linux-android` crashed QEMU. [log file](https://gist.github.com/japaric/81388f8c7880b74ea86b83e87e66d07a). cc @malbarbo 

I'm going to retry that single build job but if it fails again we'll probably have to remove `RUN=1` from that build job.

**Comment by bgermann** [comment]
Maybe it is https://github.com/rust-lang/libc/pull/825#issuecomment-340078099

**Comment by malbarbo** [comment]
Testing `i686-linux-android` locally with an update openssl worked as expected. Also it worked in the [previous](https://github.com/japaric/cross/pull/142#issuecomment-340301104) ci attempt. Did you retry @japaric?

**Comment by japaric** [comment]
> Did you retry @japaric?

I recall pushing the restart button but I think I was about to going to sleep so I forgot about looking at the result. I'll try again.

**Comment by homunkulus** [comment]
:hourglass: Testing commit 9c9bca699882f940b80ac481ea0c8a45748b6731 with merge c184a8baf57ace6506dbce1936d66c21b4ef1582...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/cross/builds/297245789?utm_source=github_status&utm_medium=notification)

**Comment by malbarbo** [comment]
openssl version 1.0.2m is available.

**Pull request closed without merging**
