### PR TITLE
add support for x86_64-musl

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit ad06f19 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit ad06f19 with merge ad06f19...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/cross/builds/186847191)

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit d1bc4b6 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit d1bc4b6 with merge d1bc4b6...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/cross/builds/186848925)
Approved by: japaric
Pushing d1bc4b606e5c7914752eda3aa35916c93ffb8dfa to master...

**Pull request merged**
