### PR TITLE
print shell commands when the verbose flag is used

### LINKED ISSUE #11: `--verbose` should print the shell commands that cross invokes

### PR DESCRIPTION
**Pull request by japaric**
closes #11

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 1cc25ac has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 1cc25ac with merge 1cc25ac...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/cross/builds/186892731)
Approved by: japaric
Pushing 1cc25ace7effce3075636cc50042ff07efb45a02 to master...

**Pull request merged**
