### PR TITLE
musl: fix type in ./configure invocation

### LINKED ISSUE #117: musl.sh typo
In [`musl.sh` line 35](https://github.com/japaric/cross/blob/d48a6dfd7ef96b17fdd6b253721b4c6a2a016eb6/docker/musl.sh#L35):
```sh
    CFLAGS="-fPIC ${@:3}" ./configure \
          --disabled-shared \
          --prefix=/usr/local \
          $(test -z $target || echo --target=$target)
```

I think `--disabled-shared` should be `--disable-shared` (note *disable**d***).

From `./configure --help`:
```
Optional features:
  --enable-optimize=...   optimize listed components for speed over size [auto]
  --enable-debug          build with debugging information [disabled]
  --enable-warnings       build with recommended warnings flags [disabled]
  --enable-visibility     use global visibility options to optimize PIC [auto]
  --enable-wrapper=...    build given musl toolchain wrapper [auto]
  --disable-shared        inhibit building shared library [enabled]
  --disable-static        inhibit building static library [enabled]
```

### PR DESCRIPTION
**Pull request by japaric**
closes #117

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit ac4498c has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit ac4498c with merge ac4498c...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/cross/builds/278109616?utm_source=github_status&utm_medium=notification)

**Comment by japaric** [comment]
wasm and asmjs are known to be broken; all the other tests passed so merging manually.

**Pull request merged**
