### PR TITLE
fix QEMU interpreter registration for custom targets

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 27b0b6f has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 27b0b6f with merge 27b0b6f...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/cross/builds/193829422)
Approved by: japaric
Pushing 27b0b6f0b3dc786321dd4382f2ef14c3759feadb to master...

**Pull request merged**
