### PR TITLE
add support for the check subcommand

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 15ac6cf has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 15ac6cf with merge 15ac6cf...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/cross/builds/239473128?utm_source=github_status&utm_medium=notification)

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 2627708 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 2627708 with merge 2627708...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/cross/builds/239580741?utm_source=github_status&utm_medium=notification)

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 7948513 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 7948513 with merge f3022fa...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/cross/builds/239803946?utm_source=github_status&utm_medium=notification)

**Comment by homunkulus** [comment]
:umbrella: The latest upstream changes (presumably 78cb295) made this pull request unmergeable. Please resolve the merge conflicts.

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit fd3c397 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit fd3c397 with merge fd3c397...

**Comment by homunkulus** [comment]
:boom: Test timed out

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit c8d3370 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit c8d3370 with merge c8d3370...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/cross/builds/278177196?utm_source=github_status&utm_medium=notification)
Approved by: japaric
Pushing c8d3370648a1f9c56a0fc4e657f155a518af9aab to master...

**Pull request merged**
