### PR TITLE
pass the QEMU_STRACE variable to docker

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

cc @tbu- With this we'll be able to strace cross compiled steed binaries, for example:

```
$ QEMU_STRACE=1 cross run --target mips-unknown-linux-steed --example _llseek
     Running `/target/mips-unknown-linux-steed/debug/examples/_llseek`
19 brk(NULL) = 0x0043d000
19 brk(0x0043d484) = 0x0043d484
19 openat(AT_FDCWD,"/target/_llseek",O_RDWR|O_CREAT|O_TRUNC|O_DIRECT|O_CLOEXEC,0666) = 3
19 ioctl(3,26113,0,0,0,0) = 0
19 write(3,0x423b5b,17) = 17
19 _llseek(3,4294967295,4294967292,0x76fff850,SEEK_CUR) = 0
19 read(3,0x76fffa24,2) = 2
19 write(1,0x76fffa24,2)me = 2
19 write(1,0x423b6c,1)
 = 1
19 close(3) = 0
19 exit(0)
```

**Comment by homunkulus** [comment]
:pushpin: Commit 9ec339a has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 9ec339a with merge 9ec339a...

**Comment by tbu-** [comment]
I could previously also strace the executables by entering the docker container, installing strace with apt-get and just calling `strace <the-executable>`. How does that differ?

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/cross/builds/195672086)

**Comment by japaric** [comment]
> How does that differ?

> by entering the docker container, installing strace with apt-get and just calling strace <the-executable>.

You won't have to do all those manual steps. Also, I believe that `strace forgein-binary` will also print the syscalls that QEMU itself invokes; whereas, this method only shows the ones from the foreign-binary.

**Comment by japaric** [comment]
The compiler-rt error has been fixed upstream.

@homunkulus retry

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 447eec3 has been approved by `japaric`

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 4c841d6 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 4c841d6 with merge 4c841d6...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/cross/builds/197892688)

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit ef635c0 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit ef635c0 with merge 2c42171...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/cross/builds/198374723)
Approved by: japaric
Pushing 2c42171c7b268b74fe2a0ae0ca72ed4e1f2b3d49 to master...

**Pull request merged**
