### PR TITLE
use `getpwuid` instead of `getlogin` to find out the user name

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus try

**Comment by homunkulus** [comment]
:hourglass: Trying commit 5dc69b0 with merge 5dc69b0...

**Comment by japaric** [comment]
@Nimamoh @jonas-schievink could you check if this fixes #33 for you?

**Comment by jonas-schievink** [comment]
Yep, seems to work, thanks for the quick fix!

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/cross/builds/188669566)
State: approved= try=True

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 5dc69b0 has been approved by `japaric`

**Pull request merged**
