### PR TITLE
Small improvements to docker images size

### PR DESCRIPTION
**Pull request by malbarbo**
Fix the removal of temporary packages and install xargo after the initial packages so that the images can share xargo install layer

### CODE REVIEW

**Comment by malbarbo** [comment]
The old code for packages removal did not work in my machine (debian 8.7). It seems that a new `purge_list` was being created...

Could xargo of the host be used instead of installing one in each image?

**Comment by japaric** [comment]
Thanks, @malbarbo!

@homunkulus r+

> Could xargo of the host be used instead of installing one in each image?

Yes, that could be done but that goes a bit against the "zero setup" nature of Cross. Unlike Cargo, not every Rust user out there has Xargo installed on their computer. Today, Cross users don't even know that Xargo is being used under the hood for some targets.

**Comment by homunkulus** [comment]
:pushpin: Commit 62b402a has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 62b402a with merge 62b402a...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/cross/builds/218919119)

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/cross/builds/218919119)
Approved by: japaric
Pushing 62b402ac46ae6f667045f1a8229d56bb7ec6e2e3 to master...

**Pull request merged**
