### PR TITLE
version info and interpreter installation

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 56da089 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 56da089 with merge 56da089...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/cross/builds/186737245)
Approved by: japaric
Pushing 56da089b29e11bb7a7249d6411f35dda51ebe0f3 to master...

**Pull request merged**
