### PR TITLE
compress cached docker artifacts

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 0aa7a80 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 0aa7a80 with merge c43e363...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/cross/builds/186812967)
Approved by: japaric
Pushing c43e363e9bfbac445509c3a5032d55a4d5a9a593 to master...

**Pull request merged**
