### PR TITLE
use Xargo v0.3.4

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 1d8cd6c has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 1d8cd6c with merge 1d8cd6c...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/cross/builds/193254522)
Approved by: japaric
Pushing 1d8cd6cf99d024a32ac4effcaee60fbfa52d2e33 to master...

**Pull request merged**
