### PR TITLE
enable the thumb targets and auto-install the rust-src component

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 550ba06 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 550ba06 with merge 550ba06...

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 501f9a6 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 501f9a6 with merge 501f9a6...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/cross/builds/187944408)

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 6fe4d35 has been approved by `japaric`

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 064d915 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 064d915 with merge 752b84d...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/cross/builds/187957364)
Approved by: japaric
Pushing 752b84d114238a9599e7027da1775ed9b5fb3774 to master...

**Pull request merged**
