### PR TITLE
add dragonfly and sparc64 environments

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 0cc2169 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 0cc2169 with merge 0cc2169...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/cross/builds/190686652)

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit a647078 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit a647078 with merge a647078...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/cross/builds/190760711)
Approved by: japaric
Pushing a647078f4156651edcf4a86240b2ddb976a71029 to master...

**Pull request merged**
