### PR TITLE
Add x86_64-linux-android build support

### PR DESCRIPTION
**Pull request by malbarbo**

### CODE REVIEW

**Comment by malbarbo** [comment]
Target x86_64-android-linux was [recently](https://github.com/rust-lang/rust/pull/41426) added.

**Comment by japaric** [comment]
Thanks, @malbarbo!

@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 528480f has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 528480f with merge 528480f...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/cross/builds/227169963?utm_source=github_status&utm_medium=notification)

**Comment by malbarbo** [comment]
The error seems to be unrelated. Let's try again?

**Comment by japaric** [comment]
The PowerPC problem should be fixed now.

@homunkulus r+

**Comment by homunkulus** [comment]
:bulb: This pull request was already approved, no need to approve it again.

- This pull request previously failed. You should add more commits to fix the bug, or use `retry` to trigger a build again.
- There's another pull request that is currently being tested, blocking this pull request: #96

**Comment by homunkulus** [comment]
:pushpin: Commit 528480f has been approved by `japaric`

**Comment by japaric** [comment]
@homunkulus retry

**Comment by homunkulus** [comment]
:hourglass: Testing commit 528480f with merge bdceaa9...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/cross/builds/233342331?utm_source=github_status&utm_medium=notification)

**Comment by malbarbo** [comment]
Unrelated again?

**Comment by japaric** [comment]
> +cargo update -p time
> error: package id specification `time` matched no packages

https://travis-ci.org/japaric/cross/jobs/227169983#L6898

**Comment by malbarbo** [comment]
I saw the wrong log, sorry. I think that chrono (and time) dependency (https://github.com/rust-lang/cargo/pull/4069) was removed in the middle of the test! That bad luck! Maybe we can fix a revision...

Fixed now.

**Comment by japaric** [comment]
Thanks. Let's try again.

@homunkulus r+

BTW, could you please next time *push* a new commit rather than amend the last one. That way it's easier for me to see the *latest* change you made.

**Comment by homunkulus** [comment]
:pushpin: Commit 125db52 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 125db52 with merge fc7b72b...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/cross/builds/234360080?utm_source=github_status&utm_medium=notification)

**Comment by malbarbo** [comment]
The problem is the new lint https://github.com/rust-lang/rust/pull/41907. How should we proceed? Use a specific version of nightly?

It seems that using nightly and head of git repositories of cargo, etc, is a fragile approach...

**Comment by malbarbo** [comment]
> BTW, could you please next time push a new commit rather than amend the last one. That way it's easier for me to see the latest change you made.

Oh, sorry for that.

**Comment by malbarbo** [comment]
@japaric How can we proceed with this?

**Comment by japaric** [comment]
There's a fix for the unused macro warning / error in rust-lang-nursery/compiler-builtins#165.

We could shield us from some of these problems using "--cap-lints" (I think that was the name of the flag) to ignore warnings / errors due to warnings.

**Comment by malbarbo** [comment]
Thanks for fixing it. According to https://github.com/rust-lang/rfcs/blob/master/text/1193-cap-lints.md the option is `--cap-lints allow`, but `cross` does not allows passing args to rustc via `RUSTFLAGS`...

**Comment by malbarbo** [comment]
Let's try again?

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:bulb: This pull request was already approved, no need to approve it again.

- This pull request previously failed. You should add more commits to fix the bug, or use `retry` to trigger a build again.

**Comment by homunkulus** [comment]
:pushpin: Commit 125db52 has been approved by `japaric`

**Comment by japaric** [comment]
@homunkulus retry

**Comment by homunkulus** [comment]
:hourglass: Testing commit 125db52 with merge e9ad79f...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/cross/builds/238557671?utm_source=github_status&utm_medium=notification)
Approved by: japaric
Pushing e9ad79f7a814b501900495544c7209053ee7ca3a to master...

**Pull request merged**
