### PR TITLE
bump qemu version to 2.9.0

### PR DESCRIPTION
**Pull request by japaric**
this should fix the powerpc failures

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 6bc8238 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 6bc8238 with merge 6bc8238...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/cross/builds/233212392?utm_source=github_status&utm_medium=notification)
Approved by: japaric
Pushing 6bc82386e1f741236e604de3b110c78823d26eeb to master...

**Pull request merged**
