### PR TITLE
CI releases and tagged docker images

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit d09c028 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit d09c028 with merge d09c028...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/cross/builds/186723603)
Approved by: japaric
Pushing d09c028349f80a4033a9f51d038d2ad307d782a7 to master...

**Pull request merged**
