### PR TITLE
add `cross run` support for the thumb targets

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 6adf911 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 6adf911 with merge 6adf911...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/cross/builds/190340426)
Approved by: japaric
Pushing 6adf911bc1bfdbc54fe422e6968c185475c8ca4f to master...

**Pull request merged**
