### PR TITLE
override the curl-sys crate

### LINKED ISSUE #4: cross hangs when building the `curl-sys` crate
for these targets

- `mips-unknown-linux-gnu`
- `mips64-unknown-linux-gnuabi64`
- `powerpc64-unknown-linux-gnu`

I have no idea why. This doesn't even involve QEMU.

cc @alexcrichton. Any tip on how to debug a build scripts that hangs/blocks? There's no output file so I can't inspect the stdout/stderr of the build script.

### PR DESCRIPTION
**Pull request by japaric**
to include alexcrichton/curl-rust#137

But only for the targets affected by #4

closes #4

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 038ecf4 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 038ecf4 with merge 038ecf4...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/cross/builds/186860054)
Approved by: japaric
Pushing 038ecf41db12da0fe18c94a1537e024c7cccc7f8 to master...

**Pull request merged**
