### PR TITLE
support older versions of the openssl crate

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit e972216 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit e972216 with merge 40552ae...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/cross/builds/191840695)

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 51f37c5 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 51f37c5 with merge 57f1f6d...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/cross/builds/191896329)
Approved by: japaric
Pushing 57f1f6d5232817bb2b7f774d7df1d626b2a4819f to master...

**Pull request merged**
